-- =====================================================================
-- StayFlow Staff — 0014 re-assert the audit-log guarantee
--
-- A migration generated by `supabase db pull` (20260727080126_remote_commit)
-- was applied to the hosted project. Among nineteen lines of otherwise
-- harmless storage and realtime triggers, it contained:
--
--     grant delete on table "public"."audit_logs" to "authenticated";
--     grant insert on table "public"."audit_logs" to "authenticated";
--     grant update on table "public"."audit_logs" to "authenticated";
--
-- which hands every signed-in staff member the ability to forge, alter or
-- destroy audit entries — the exact opposite of what 0001, 0006 and 0008
-- exist to guarantee.
--
-- The file was deleted locally once spotted, but deleting a migration does
-- not undo what already ran on a database that applied it. This migration
-- does.
--
-- Written to be idempotent and safe to apply anywhere: on a database that
-- never had the bad grants, every statement below is a no-op.
-- =====================================================================

-- ---------------------------------------------------------------------
-- audit_logs: readable by owners, appended only by SECURITY DEFINER
-- triggers, and never modified by anybody.
-- ---------------------------------------------------------------------
revoke insert, update, delete, truncate on audit_logs from anon, authenticated;

-- service_role may append (the trigger path) but still may not rewrite
-- history, matching the rule established in 0008.
revoke update, delete, truncate on audit_logs from service_role;

-- ---------------------------------------------------------------------
-- clock_events: the same guarantee, for the same reason.
--
-- Attendance is the other append-only record, and a pull-generated
-- migration could just as easily have re-granted it.
-- ---------------------------------------------------------------------
revoke update, delete, truncate on clock_events from anon, authenticated;
revoke update, delete, truncate on clock_events from service_role;

-- ---------------------------------------------------------------------
-- Guard against a repeat.
--
-- `supabase db pull` diffs the remote against local and writes whatever it
-- finds back as a migration. When the remote is ahead — or simply carries
-- Supabase's stock default grants — that diff can re-grant precisely what
-- was deliberately revoked. Default privileges make the intent stick for
-- objects created later, so a future pull has nothing to "restore".
-- ---------------------------------------------------------------------
alter default privileges in schema public
  revoke truncate on tables from anon, authenticated;

comment on table audit_logs is
  'Append-only record of significant events. INSERT/UPDATE/DELETE/TRUNCATE
   are revoked from anon and authenticated, and UPDATE/DELETE/TRUNCATE from
   service_role, so history cannot be rewritten by any application path.
   Re-asserted in 0014 after a `db pull` migration re-granted them on the
   hosted project.';
